#!/usr/bin/env python3
"""make-router.py — generate ROUTER.md (≤ 2 KB) from the practices' frontmatter, so that an agent in another repo
can route in one short read instead of fourteen thousand tokens of prose (decision 0004 §5).
Usage: python3 scripts/make-router.py            # writes ROUTER.md
       python3 scripts/make-router.py --check    # exit 1 if ROUTER.md is stale (run by kb-check.sh)
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from applies import ROOT, practices  # noqa: E402

LIMIT = 2048

def render():
    rows = practices()
    out = ["# ROUTER — generated by scripts/make-router.py; do not edit", "",
           "Facts (practices/facts.md) → `python3 scripts/applies.py --explain <facts…>` → ordered list. Existing repo: playbooks/which-practices-apply.md. Blank repo: playbooks/bootstrap-new-repo.md. Implement one: practices/prompt-library/implement-practice.md. Evidence: practices/adoptions.md.", "",
           "| practice | kind | applies-when | full-when | when | ref |", "|---|---|---|---|---|---|"]
    for p in rows:
        kind = "ws" if p["kind"] == "working-style" else "cap"
        out.append(f"| {p['name']} | {kind} | {p['applies']} | {p['full'] or ''} | {p['when']} | {p['ref']}{'' if p['status']=='current' else ' ('+p['status']+')'} |")
    out += ["", "ws = working-style (any repo an agent works in); cap = capability (depends on what the product does). when = day-0 | first-user | at-scale. ref = reference-status: untested | field-tested | reference. A practice folder with no row here is draft and unrouted (decision 0004 §6).", ""]
    text = "\n".join(out)
    if len(text.encode("utf-8")) > LIMIT:
        sys.stderr.write(f"ROUTER.md would be {len(text.encode('utf-8'))} bytes > {LIMIT}\n"); sys.exit(1)
    return text

if __name__ == "__main__":
    text = render(); path = os.path.join(ROOT, "ROUTER.md")
    if "--check" in sys.argv:
        current = open(path, encoding="utf-8").read() if os.path.exists(path) else ""
        if current != text:
            print("  - ROUTER.md is stale: run python3 scripts/make-router.py"); sys.exit(1)
        sys.exit(0)
    open(path, "w", encoding="utf-8").write(text); print(f"ROUTER.md written ({len(text.encode('utf-8'))} bytes)")
