#!/usr/bin/env python3
"""make-bundles.py — generate practices/bundles.md: for each of the four shapes, the practice list a BLANK repo gets
(the shape's facts as *planned*, so only day-0 practices attach) and the list an EXISTING repo of that shape gets
(facts inferred), both from scripts/applies.py — plus the hand-written stack defaults embedded from
practices/stack-defaults.md. Decision 0004 §3: a generated list cannot drift; the stack section is validated by
kb-check's link check (every path it names must exist).
Usage: python3 scripts/make-bundles.py [--check]
"""
import os, re, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from applies import ROOT, SHAPES, facts_vocabulary, practices, route  # noqa: E402

def fmt(res):
    lines = [f"  {i}. {r['name']} [{r['when']}; ref {r['ref']}{'' if r['status']=='current' else '; '+r['status']}]" for i, r in enumerate(res["working_style"] + res["capability_and_full"], 1)]
    if res["deferred"]: lines.append("  deferred until inferred: " + ", ".join(r["name"] for r in res["deferred"]))
    lines.append("  skipped: " + (", ".join(r["name"] for r in res["skipped"]) or "—"))
    return "\n".join(lines)

def render():
    vocab = facts_vocabulary(); plist = practices()
    defaults = open(os.path.join(ROOT, "practices", "stack-defaults.md"), encoding="utf-8").read()
    body = defaults.split("\n---\n", 2)[-1]  # drop frontmatter
    body = body.split("## Change log")[0].rstrip()
    out = ["# Bundles — generated by scripts/make-bundles.py from scripts/applies.py and practices/stack-defaults.md; do not edit", "",
           "A bundle = the practice list for a shape (generated) + the stack defaults for it (hand-written in practices/stack-defaults.md). "
           "**Blank repo**: the shape's facts are *planned* (`brownfield` and `production` off; the two asked facts assumed \"no\" — answer them for real), so only `day-0` practices attach and the rest are deferred until the code shows the fact or the product has users. "
           "**Existing repo**: the same facts inferred. Both lists come from `python3 scripts/applies.py`; run it with the repo's real facts rather than trusting a shape.", ""]
    for title, fstr in SHAPES.items():
        facts = fstr.split()
        planned = [f + ":planned" for f in facts if f not in ("brownfield", "production", "parallel_sessions", "long_tasks")]  # blank: not in production yet; the two asked facts assumed "no"
        out += [f"## {title}", "", f"facts: `{fstr}`", "", "**Blank repo (planned facts, day-0 only):**", "", fmt(route(planned, vocab, plist)), "",
                "**Existing repo (facts inferred):**", "", fmt(route(facts, vocab, plist)), ""]
    out += ["---", "", "# Stack defaults (from practices/stack-defaults.md)", body, ""]
    return "\n".join(out)

if __name__ == "__main__":
    text = render(); path = os.path.join(ROOT, "practices", "bundles.md")
    if "--check" in sys.argv:
        cur = open(path, encoding="utf-8").read() if os.path.exists(path) else ""
        if cur != text: print("  - practices/bundles.md is stale: run python3 scripts/make-bundles.py"); sys.exit(1)
        sys.exit(0)
    open(path, "w", encoding="utf-8").write(text); print(f"practices/bundles.md written ({len(text)} chars)")
