#!/usr/bin/env python3
"""make-router.py — generate ROUTER.md (≤ 2 KB) from the practices' frontmatter, so that an agent in another repo
can route in one short read instead of fourteen thousand tokens of prose (decision 0004 §5).
Usage: python3 scripts/make-router.py            # writes ROUTER.md
       python3 scripts/make-router.py --check    # exit 1 if ROUTER.md is stale (run by kb-check.sh)
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from applies import ROOT, practices  # noqa: E402

LIMIT = 2048

def render():
    rows = practices()
    out = ["# ROUTER — generated by scripts/make-router.py; do not edit", "",
           "Facts (practices/facts.md) → `scripts/applies.py --explain <facts…>` → ordered list. Existing repo: playbooks/which-practices-apply.md; blank: playbooks/bootstrap-new-repo.md; implement: practices/prompt-library/implement-practice.md; evidence: practices/adoptions.md.", "",
           "| practice | k | applies-when | full-when | when | ref |", "|---|---|---|---|---|---|"]
    WHEN = {"day-0": "d0", "first-user": "fu", "at-scale": "as"}
    REF = {"untested": "u", "field-tested": "ft", "reference": "r"}
    for p in rows:
        kind = "ws" if p["kind"] == "working-style" else "cap"
        v = ("; " + ", ".join(f"{k}={s}" for k, s in p["variants"].items())) if p["variants"] else ""
        full = (p['full'] or '').replace(p['applies'] + ' and ', '… and ')
        out.append(f"| {p['name']} | {kind} | {p['applies']} | {full} | {WHEN.get(p['when'], p['when'])} | {REF.get(p['ref'], p['ref'])}{v}{'' if p['status']=='current' else ' D'} |")
    out += ["", "k: ws working-style, cap capability. when: d0 day-0, fu first-user, as at-scale. ref: u untested, ft field-tested, r reference (+ field-tested variants per stack); D = status draft. '…' = applies-when. All reviewed practices listed (decision 0006); no row = still being written.", ""]
    text = "\n".join(out)
    if len(text.encode("utf-8")) > LIMIT:
        sys.stderr.write(f"ROUTER.md would be {len(text.encode('utf-8'))} bytes > {LIMIT}\n"); sys.exit(1)
    return text

if __name__ == "__main__":
    text = render(); path = os.path.join(ROOT, "ROUTER.md")
    if "--check" in sys.argv:
        current = open(path, encoding="utf-8").read() if os.path.exists(path) else ""
        if current != text:
            print("  - ROUTER.md is stale: run python3 scripts/make-router.py"); sys.exit(1)
        sys.exit(0)
    open(path, "w", encoding="utf-8").write(text); print(f"ROUTER.md written ({len(text.encode('utf-8'))} bytes)")
